cache:
  directories:
    - node_modules
notifications:
  email: true
language: node_js
node_js:
  - '14'
  - '15'
  - '16'
before_script:
  - npm prune
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
script:
  - npm run lint
  - npm test
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run report
  - npm run codecov
  - npm run docs
  - git config --global user.name "JamesCullum (Pseudonym)"
  - git config --global user.email "https://mailhide.io/e/Wno7k"
  - npm run publish-docs

deploy:
  provider: npm
  email: "blasium110+npm@gmail.com"
  api_token: $NPM_AUTH_TOKEN
  edge: true
  on:
    branch: master